<script lang="ts">
  import {
    ArrowLeft,
    ArrowDown,
    BrainCircuit,
    BookOpen,
    Bot,
    Check,
    ChevronDown,
    ChevronsUp,
    CircleAlert,
    CircleHelp,
    Component as ComponentIcon,
    ClipboardList,
    Copy,
    Cpu,
    Database,
    Download,
    ExternalLink,
    Eye,
    EyeOff,
    FileCode,
    FileDown,
    FileJson,
    FileText,
    FlaskConical,
    Globe,
    Globe2,
    GraduationCap,
    Home,
    Info,
    KeyRound,
    Link,
    ListChecks,
    LogIn,
    LogOut,
    Mail,
    MailPlus,
    MapPin,
    Menu,
    MessageSquare,
    MessageCircle,
    Microscope,
    Monitor,
    Palette,
    Phone,
    Route,
    Search,
    Send,
    ShieldCheck,
    Sparkle,
    Sparkles,
    Spline,
    Star,
    Table,
    Target,
    ThumbsDown,
    ThumbsUp,
    Trash2,
    Upload,
    Users,
    X,
    Zap
  } from '@lucide/svelte'
  import Github from '$lib/components/icons/GithubIcon.svelte'
  import type { Component } from 'svelte'

  interface Props {
    name: string
    class?: string
  }

  let { name, class: className = '' }: Props = $props()

  const iconMap: Record<string, Component> = {
    'i-lucide-arrow-left': ArrowLeft,
    'i-lucide-arrow-down': ArrowDown,
    'i-lucide-brain-circuit': BrainCircuit,
    'i-lucide-book-open': BookOpen,
    'i-lucide-bot': Bot,
    'i-lucide-check': Check,
    'i-lucide-chevron-down': ChevronDown,
    'i-lucide-chevrons-up': ChevronsUp,
    'i-lucide-circle-alert': CircleAlert,
    'i-lucide-component': ComponentIcon,
    'i-lucide-clipboard-list': ClipboardList,
    'i-lucide-copy': Copy,
    'i-lucide-cpu': Cpu,
    'i-lucide-database': Database,
    'i-lucide-download': Download,
    'i-lucide-external-link': ExternalLink,
    'i-lucide-eye': Eye,
    'i-lucide-eye-off': EyeOff,
    'i-lucide-file-code': FileCode,
    'i-lucide-file-down': FileDown,
    'i-lucide-file-json': FileJson,
    'i-lucide-file-text': FileText,
    'i-lucide-flask-conical': FlaskConical,
    'i-lucide-globe': Globe,
    'i-lucide-globe-2': Globe2,
    'i-lucide-graduation-cap': GraduationCap,
    'i-lucide-home': Home,
    'i-lucide-github': Github,
    'i-lucide-help-circle': CircleHelp,
    'i-lucide-info': Info,
    'i-lucide-key-round': KeyRound,
    'i-lucide-link': Link,
    'i-lucide-list-checks': ListChecks,
    'i-lucide-log-in': LogIn,
    'i-lucide-log-out': LogOut,
    'i-lucide-mail': Mail,
    'i-lucide-mail-plus': MailPlus,
    'i-lucide-map-pin': MapPin,
    'i-lucide-menu': Menu,
    'i-lucide-message-circle': MessageCircle,
    'i-lucide-message-square': MessageSquare,
    'i-lucide-messages-square': MessageSquare,
    'i-lucide-microscope': Microscope,
    'i-lucide-monitor': Monitor,
    'i-lucide-palette': Palette,
    'i-lucide-phone': Phone,
    'i-lucide-route': Route,
    'i-lucide-search': Search,
    'i-lucide-send': Send,
    'i-lucide-shield-check': ShieldCheck,
    'i-lucide-sparkle': Sparkle,
    'i-lucide-sparkles': Sparkles,
    'i-lucide-spline': Spline,
    'i-lucide-star': Star,
    'i-lucide-table': Table,
    'i-lucide-target': Target,
    'i-lucide-thumbs-down': ThumbsDown,
    'i-lucide-thumbs-up': ThumbsUp,
    'i-lucide-trash-2': Trash2,
    'i-lucide-upload': Upload,
    'i-lucide-users': Users,
    'i-lucide-x': X,
    'i-lucide-zap': Zap
  }

  const Icon = $derived(iconMap[name] ?? CircleHelp)
</script>

<Icon class={className} aria-hidden="true" focusable="false" />
