// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/admin/candidates/:id': {
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/candidates/[id].patch').default>>>>
    }
    '/api/admin/candidates': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/candidates/index.get').default>>>>
    }
    '/api/admin/invites': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/invites.post').default>>>>
    }
    '/api/admin/me': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/me.get').default>>>>
    }
    '/api/chat': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/chat.post').default>>>>
    }
    '/api/chat/feedback': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/chat/feedback.post').default>>>>
    }
    '/api/chat/web': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/chat/web.post').default>>>>
    }
    '/api/faq': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/faq.get').default>>>>
    }
    '/api/health/db': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/health/db.get').default>>>>
    }
    '/api/perguntas/em-alta': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/perguntas/em-alta.get').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/api/_nuxt_icon/:collection': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/icon/dist/runtime/server/api').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}